### PR TITLE
Add the license

### PR DESCRIPTION
**Pull request by tacotexmex**

### CODE REVIEW

**Comment by bosapara** [comment]
No need.

**Comment by tacotexmex** [comment]
No license stated = no rights. It's not open source until you choose a license.

Your unwillingness to explicitly state the license (even if WTFPL) will give your mods a shorter lifespan as no-one will want to fork without a clear license. It's just bad.

**Comment by bosapara** [comment]
no-one will want to fork without a clear license<<
**Alright, this is an argument. License will be added.**

**Comment by tacotexmex** [comment]
Thank you!

**Pull request closed without merging**
